#!/bin/bash
# This script is a poor mans version of the symbolic link
# that is normally here to facilitate running bpipe from the root directory 
# of the distribution
unset GROOVY_HOME
set -f
CMD=`echo "$0" | sed 's/bpipe/tools\/bpipe\/bin\/bpipe/'`
$CMD $*
