requires 'HTTP::Tiny', '== 0.056';
requires 'LWP::Simple', '== 6.15';
requires 'Archive::Zip', '== 1.56';
requires 'DBI', '== 1.636';
requires 'LWP::Protocol::https', '== 6.04';
requires 'File::Copy::Recursive', '== 0.38';
requires 'Archive::Extract', '== 0.78';
requires 'CGI', '== 4.32';
requires 'Bio::DB::HTS', '== 2.4';
