#!/usr/bin/env python
'''
  Removes negative regions from the bed file, which may have been generated by bedtools slop
  Usage: python filter_bed.py < bed_file > filtered_bed_file
'''

import sys

def filter_bed( fh_in, fh_out ):
  for line in fh_in:
    if line.startswith('#'):
      fh_out.write( line )
    else:
      fields = line.split('\t')
      if len(fields) > 2:
        if int(fields[2]) > int(fields[1]):
          fh_out.write( line )
        else:
          pass # filter negative
          #fh_out.write( '#{0}'.format( line ) )
      else:
        fh_out.write( line )

if __name__ == '__main__':
  filter_bed( sys.stdin, sys.stdout )
